version: "3.8"
services:
  order-mysql-service:
    image: mysql:latest
    restart: always
    container_name: order_mysql_db
    environment:
      MYSQL_DATABASE: order_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - order-network

  order-service:
    container_name: order_management_app
    image: order-management:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - order-mysql-service
    environment:
      ACTIVE_PROFILE: dev
      DB_URL: jdbc:mysql://order-mysql-service:3306/order_db
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - order-network
    restart: on-failure

networks:
  order-network:
    driver: bridge
volumes:
  db-data: